package top.niunaijun.blackbox.core.system;

import android.os.Binder;

import top.niunaijun.blackbox.core.system.user.IBUserManagerService;

/**
 * Stub base for BUserManagerService IPC.
 */
public abstract class IBUserManagerStub extends Binder
        implements IBUserManagerService {
    // Stub implementation – real IPC generated by AIDL
}
